[package]
name = "gogdl-lib"
version = "0.5.0"
edition = "2024"
license = "GPL-3.0-only"

[features]
default = ["rustls"]
rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

[dependencies]
chrono = "0.4.43"
filetime = "0.2.27"
flate2 = { version="1.1.5", default-features = false, features = ["zlib-rs"]}
futures = "0.3.31"
futures-util = "0.3.31"
hex = "0.4.3"
md5 = "0.8.0"
reqwest = { version = "0.12.25", default-features = false, features = ["stream", "rustls-tls"] }
serde = { version = "1.0.228", default-features = false, features = ["derive"] }
serde_json = "1.0.145"
sha2 = "0.10.9"
thiserror = "2.0.17"
tokio = { version = "1.48.0", default-features = false, features = ["rt-multi-thread", "fs", "macros"] }
tokio-util = { version = "0.7", default-features = false }
url = "2.5.7"
uuid = { version = "1.20.0", default-features = false, features = ["v4"] }
